In [2]:
import numpy as np

In [48]:
a = np.array([1, 2, 3], dtype='int32')

In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension:

In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [11]:
# Get Shape
a.shape

(3,)

In [12]:
b.shape

(2, 3)

###### Get Type of arrays:
a.dtype

In [15]:
# Get Type of arrays:
a.dtype

dtype('int32')

In [16]:
# Get size:
a.itemsize

4

In [17]:
a.nbytes

12

In [22]:
a = np.array([[1,2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [19]:
# get a specific element

In [24]:
a[1, 4]

10

In [25]:
# Get specific row

In [26]:
a[0, :]

array([1, 2, 3, 4, 5])

In [27]:
# Get specific col

In [28]:
a[:, 2]

array([3, 8])

In [30]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4])

In [31]:
a[0, 1:4:2]

array([2, 4])

In [32]:
a[1, 4] = 90

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 90]])

In [34]:
a[:, 2] = [1, 2]

In [35]:
print(a)

[[ 1  2  1  4  5]
 [ 6  7  2  9 90]]


In [36]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [38]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [45]:
# replace 
b[:, 1, :] = [[9,9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [47]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# All 1s matrix
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [51]:
# for any other number than 1 and 0, you have to use np.full()

In [60]:
np.full((2, 2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [65]:
np.full(a.shape, 4)

array([4, 4, 4])

In [69]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.1365166 , 0.91528967],
       [0.60915206, 0.96040026],
       [0.67675073, 0.43976209],
       [0.55067355, 0.55606648]])

In [75]:
# Random Integer Values
np.random.randint(-4, 8, size=(3, 3))

array([[-1,  2,  3],
       [ 6,  7,  5],
       [ 7, -4, -1]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [95]:
output = np.ones((5, 5))
print(output)
z = np.zeros((3, 3))
z[1, 1]
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [102]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [104]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [112]:
a += 2
a

array([ 7,  8,  9, 10])

In [106]:
a - 2

array([-1,  0,  1,  2])

In [107]:
a*2

array([2, 4, 6, 8])

In [109]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [114]:
b = np.array([1, 0, 1, 0])
a + b

array([ 8,  8, 10, 10])

In [115]:
a - b 

array([ 6,  8,  8, 10])

In [116]:
a ** 2

array([ 49,  64,  81, 100])

In [118]:
# Take the sin
np.cos(a)

array([ 0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [125]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)


np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [127]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [128]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
np.min(stats, axis = 1)

array([1, 4])

In [132]:
np.max(stats, axis = 1)

array([3, 6])

In [133]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [155]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print('#######')
after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
#######
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [164]:
# vertical stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [168]:
# Horizontal Stack 
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
h1
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [178]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.]])

#### Boolean masking and indexing

In [180]:
filedata[filedata > 2]

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,
       16.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16.])

In [186]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

np.all(filedata > 50, axis=1)

array([False, False, False, False])

In [188]:
((filedata > 2) & (filedata < 100))

array([[False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
# if your matrix looks like: [
# [1, 2, 3, 4, 5]
# [6, 7, 8, 9, 10]
# [11, 12, 13, 14, 15]
# [16, 17, 18, 19, 20]
# [21, 22, 23, 24, 25]
# [26, 27, 28, 29, 30]
# ]
# ]
# a[2:4, 0:2]
# a[[0, 1, 2, 3], [1, 2, 3, 4]]
# a[[0, 4, 5], 3:]















# The way to access 11, 12, 16, 17 together would be: a[2:4, 0:2], 
# to access 2, 8, 14, 20 together : a[[0, 1, 2, 3], [1, 2, 3, 4]]
# to access 4, 5, 24, 25, 29, 30 togehter: a[[0, 4, 5], 3:]